name: tests-tickets

on:
  pull_request:
    paths:
      - 'tickets/**' #specifically run this test only when any change happens in the tickets dir
jobs:
  build: #create a container
    runs-on: ubuntu-latest #use ubuntu as the virual machine os
    steps:
      - uses: actions/checkout@v2 #takes all the code in our project
      # goes in tickets dir then run npm install then runs all the tests only once and that is the ci for
      - run: cd tickets && npm install && npm run test:ci
